"""Add admin relationship to Sacco

Revision ID: 0ca3921bf8a4
Revises: 518b15b5689e
Create Date: 2026-02-24 16:43:22.579763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ca3921bf8a4'
down_revision = '518b15b5689e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saccos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_saccos_admin_id', 'users', ['admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saccos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_saccos_admin_id', type_='foreignkey')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###
